### PR TITLE
Add SchildiChat to clients

### LINKED ISSUE #276: Add SchildiChat
SchildiChat (https://schildi.chat/) is an Element mod with user-friendly features. It is available on Android (both F-droid and Google Play), desktop and as a web app.

### PR DESCRIPTION
**Pull request by Zocker1999NET**
- fixes #276
- PR will be checked by SchildiChat devs, then the PR will be marked as ready
- Compatibility of redirects were tested on Linux Desktop & Android (with the F-Droid version)

image
(description was updated in code)

### CODE REVIEW

**Comment by SpiritCroc** [comment]
Tested, links appear to work here on desktop and Android for me as well. We're planning to change the SchildiChat description soon, I think we should block this until we have decided on the new one.

**Comment by SpiritCroc** [comment]
ok, so following two things, then should be good to go from our side:
- Update description: https://raw.githubusercontent.com/SchildiChat/SchildiChat-android/5bbd462cdbecf64ceda7e65e8cd8a4e241bfca03/fastlane/metadata/android/en-US/short_description.txt
- We now also have test.schildi.chat hosted for beta builds of SchildiChat web, would be great if you can add this to trusted instances.

**Comment by Zocker1999NET** [comment]
@SpiritCroc I implemented your changes. Hope it is correct for you know

**Comment by SpiritCroc** [comment]
> > (didn't update the image for now)
> 
> Does "image" mean the logo of the app? Does this mean the image is not up to date?

We haven't changed the logo since the initial PR, still looks up-to-date to me.

**Comment by Zocker1999NET** [comment]
> Does "image" mean the logo of the app? Does this mean the image is not up to date?

"Image" refers to the example image in the PR's top description, which shows an old version of the description for SchildiChat

**Pull request merged**
