### PR TITLE
Add fluffychat://#room and fluffychat://@user URIs

### PR DESCRIPTION
**Pull request by ChristianPauly**
On a Ubuntu Touch device with fluffychat installed, you can click on these URIs and it will open fluffychat automatically.

### CODE REVIEW

**Comment by KitsuneRal** [comment]
Can we please do https://github.com/matrix-org/matrix-doc/issues/455 instead?

**Comment by aaronraimist** [comment]
@KitsuneRal yes that is the dream but it isn't here yet. the matrix.to page itself says

"Links are designed to be human-friendly, both for reading and constructing, and are essentially a compatibility step in the journey towards a ubiquitous mx:// URL scheme."

I'd say merge this for now and then when mx:// is here you won't really need matrix.to anymore.

**Comment by KitsuneRal** [comment]
@aaronraimist, it's not a dream; it's a design that, it seems, only me is really pushing forward. If this goes in, I'll have to quickly draft `quaternion://` (and `spectral://`, serving interests of QMatrixClient ecosystem) in a similar vein.
So can we please mature https://github.com/matrix-org/matrix-doc/issues/455 instead and then add `mx://` to matrix.to? "Not needing" matrix.to is not going to happen anytime soon, now that we have plenty of links with it already in room DAGs.

**Comment by aaronraimist** [comment]
It's a dream in the sense that everyone wants it but it doesn't exist. I'm with you that yes it should exist.

I'm not anyone special so all I can do (and did do months ago) is upvote that issue.

What can be done to push that proposal forward? Don't you need to write it up as an MSC? (I'm not familiar enough with the process, yes there is an issue but don't you need to PR?)

**Comment by benparsons** [comment]
We should not have delayed on merging this. Are there any reasons not to accept a request like this, even knowing that matrix-org/matrix-doc#455 remains the true end-goal?

**Comment by KitsuneRal** [comment]
Why not add matrix://, again?

**Comment by benparsons** [comment]
The intention is always to add matrix://, but right now, that would mean waiting on MSC455. Would it be appropriate to introduce matrix:// before then? If not, then there seems to be no reason to block use of fluffychat:// while waiting.

**Comment by aaronraimist** [comment]
@kitsuneral is there any status update on matrix://? It would be nice to push that along. Are you waiting on others to try implementing it?

**Comment by KitsuneRal** [comment]
I agree the entire thing is well overdue, so here goes.
1. I don't see why we can't add `matrix:` (or even `mx:`) scheme at this stage. The scheme defined in the MSC is now down to a single option, and this option hasn't really evolved for the last few months. It needs not be final to be added to matrix.to; moreover, I think it's time to give a bit of testing by adding it to matrix.to.
2. To that end, I have just enabled Quaternion to open matrix: URIs in-application: https://github.com/quotient-im/Quaternion/commit/a711e60525d4932821ce0cf60107c694369fef8f

Let's push that envelope already.

**Comment by ChristianPauly** [comment]
fluffychat:// is just a workaround for a bug in Ubuntu Touch which prevents https links in the url-dispatcher. I'm not sure if this is my fault or its a bug in the system itself (documentation is not that clear for me). However in the future I would also like to replace it with a more universal solution.

**Comment by aaronraimist** [comment]
Looks like it may be possible to merge this considering opening Riot will soon use a riot:// or web+riot:// url scheme. See https://matrix.to/#/!ekJXCOhsmAWQUMhDgn:riot.ovh/$1590784950505naIwB:riot.ovh?via=riot.ovh&via=matrix.org&via=mozilla.org and above convo for some more information.

**Comment by bwindels** [comment]
Closing as the api to add a client has changed. Please resubmit if still interested.

**Pull request closed without merging**
