### PR TITLE
Add Matrix Static to the new site

### PR DESCRIPTION
**Pull request by aaronraimist**
Fixes https://github.com/matrix-org/matrix.to/issues/136

Things to be done:
- [x] Need to fix logo, currently gets cut off weirdly

- [x] It should only say Web, not Web & Desktop
- [ ] Hide Matrix Static when the link is to a user

For reference here is what the old matrix.to used for the Matrix Static entry https://github.com/matrix-org/matrix.to/blob/0c6343c5769057392678cab4a5680a28d74e935a/src/components/HomePage.js#L37-L44

### CODE REVIEW

**Comment by aaronraimist** [comment]
Hmm the indentation is all off because my text editor trusted the `.editorconfig` file but many of the files don't follow that format

**Comment by aaronraimist** [comment]
I'm not sure how to hide it when a username is entered

**Comment by bwindels** [comment]
Thanks for the PR. We'll want to add matrix static back not as a client though, but put a dedicated link somewhere. Will need design input.

**Comment by MurzNN** [comment]
Maybe at least add it as client, if implementation is already ready, and add dedicated link as next step? 6 months have passed, but we still miss that link :(

**Pull request closed without merging**
