### PR TITLE
Initial MSC3266 implementation with tweaks for displaying Spaces

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/matrix-org/matrix.to/issues/213
Fixes https://github.com/matrix-org/matrix.to/issues/214
Implements https://github.com/matrix-org/matrix-doc/pull/3266

image

### CODE REVIEW

**Review by turt2live — CHANGES_REQUESTED** [review]
I'm sure the code is fine, but the mix of tabs and spaces makes this aggravating to review. Please fix it across the whole project, as I can see historical diffs with tabs/spaces issues as well - I'd rather one PR be overloaded than review this indentation nightmare.

**Review by novocaine — APPROVED** [review]

**Comment by t3chguy** [comment]
Going to hold off landing this until Synapse has support for it, as it does add an additional API hit so a tiny bit of delay to HSes without support for this API - it is negligible but we gain nothing from landing it early

**Review by turt2live — APPROVED** [review]

**Review by mike22664 — APPROVED** [review]

**Comment by t3chguy** [comment]
The Synapse MSC is getting close and I'm going on holiday, merging now, no rush on deploy, will create a card re deploying closer to go live

**Comment by clokep** [comment]
FYI the required APIs are now live on matrix.org, it sounds like we'll want to wait for it to be in a release version before deploying though since (I think) matrix.to hits various homeservers?

**Comment by novocaine** [comment]
Yes, the first time you use matrix.to we ask you which homeserver to use to show previews.. 

Screenshot 2021-08-18 at 17 24 43

(to be honest, this doesn't seem worth the likely drop-off just to show summaries ..)

**Comment by ara4n** [comment]
the idea is that the "use matrix.org?" dialog should feel no more or less invasive than a GDPR click-thru fwiw.  previews are pretty important UX though - in terms of room name, avatar, etc, otherwise it could just come up with a raw ID which is horrific.

**Pull request merged**
