### PR TITLE
Add matrix:chat badge

### PR DESCRIPTION
**Pull request by strk**
See #20

NOTE: this commit only adds the (improvable) badge, but does not
      show it yet on the page

### CODE REVIEW

**Comment by bbigras** [comment]
Any interest in this? We see those gitter badges everywhere and people use them. This could help publicize matrix a little bit.

**Comment by strk** [comment]
In case it helps, while this PR is not merged I've been using shields.io to generate badges on the fly, for example: `https://img.shields.io/badge/matrix-%23gitea%3Amatrix.org-7bc9a4.svg`

**Comment by richvdh** [comment]
will try to remember to do something about this next week

**Comment by richvdh** [comment]
Thank you for this. Now available at https://matrix.to/img/matrix-badge.svg.

In an ideal world, matrix.to would provide a badge generation service as per #3, but we're happy to provide this as a stop-gap until someone can write a badge generation service for us :)

**Pull request merged**
