### PR TITLE
Add note about #matrix.to:riot.ovh

### PR DESCRIPTION
**Pull request by aaronraimist**
Had no idea any related rooms existed until today

Also changes an old Jira link to the new GitHub issue

### CODE REVIEW

**Comment by t3chguy** [comment]
I will arrange a `:matrix.org` alias for this room tonight, better than a `:riot.ovh` in case my HS drops out of existence

**Comment by aaronraimist** [comment]
Done

**Comment by aaronraimist** [comment]
Signed-off-by: Aaron Raimist <aaron@raim.ist>

**Comment by t3chguy** [comment]
Thanks!

**Pull request merged**
